# Generated by Django 6.1 on 2026-08-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("status", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("error_info", models.TextField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statements.transaction",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProcessedTransaction",
        ),
    ]
