# Generated by Django 6.1 on 2026-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("transaction_type", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_date", models.DateTimeField()),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("operator", models.CharField(blank=True, max_length=50, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
