# Generated by Django 5.2.17 on 2026-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('file_transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('details_1', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('masked_account', models.CharField(blank=True, max_length=50, null=True)),
                ('details_2', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_time', models.DateTimeField()),
                ('details_3', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_value', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_details_2', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_details', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
